### ISSUE TITLE
oserr.nim(95)raiseOSError

### ISSUE THREAD

**Issue by Pen-Ace** [Primusinterp/PrimusC2#1]
Hey,

Got this working all the way until I await a callback. Get a error on the windows host:

oserr.nim(95)raiseOSError
![image](https://github.com/Primusinterp/PrimusC2/assets/25384439/dc263197-95f0-4979-9451-ba33ae8091f1)

Any idea what could be the issue? 

Both the attacking box and the victim can successfully ping each other and are set to a bridged adapter. Additionally, I've disabled the firewall and antivirus as a precaution, but the issue persists.

Safe.

**Comment by Pen-Ace** [comment]
Quick update, I discovered that to resolve the issue, I must disable the Windows Defender firewall and then regenerate the payload.

**Comment by Primusinterp** [comment]
Hi Pen-Ace 

Glad to hear it worked out!

I haven't encountered any issues with Windows Defender Firewall - can you test if this error still occurs after you regenerated the payload with Windows Defender Firewall on?
