### ISSUE TITLE
ERROR: Could not open requirements file:

### ISSUE THREAD

**Issue by kali64amd** [Primusinterp/PrimusC2#2]
hi, there

It's strange I'm getting this error and I don't know why?? I checked everything has been installed as per requirements file however still got this error

########################################################################
[*] Installing python requirements...
########################################################################
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/shinobix/PrimusC2/requirements.txt'

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------

──(shinobix㉿shinobix)-[~/Desktop/Tool/PrimusC2]
└─$ source setup.sh               
########################################################################
[+] Installing dependecies...
########################################################################
Hit:1 https://brave-browser-apt-release.s3.brave.com stable InRelease
Hit:2 http://kali.cs.nycu.edu.tw/kali kali-rolling InRelease
Hit:3 https://deb.i2p2.de unstable InRelease   
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
6 packages can be upgraded. Run 'apt list --upgradable' to see them.
W: https://deb.i2p2.de/dists/unstable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  gir1.2-gtksource-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 gobject-introspection king-phisher libavfilter8 libavformat59
  libblockdev-crypto2 libblockdev-fs2 libblockdev-loop2 libblockdev-part-err2 libblockdev-part2 libblockdev-swap2 libblockdev-utils2 libblockdev2 libcodec2-1.0
  libgdal32 libgeos3.11.1 libhttp-cookiejar-perl liblc3-0 libmongocrypt0 libmozilla-publicsuffix-perl libmujs2 libncurses5 libplacebo208 libpostproc56
  libsoup-gnome2.4-1 libspatialite7 libsuperlu5 libswscale6 libtinfo5 libwebsockets17 linux-image-6.1.0-kali7-amd64 pwgen python3-advancedhttpserver python3-boltons
  python3-cairo-dev python3-cryptography37 python3-flask-security python3-geoip2 python3-geojson python3-graphene python3-graphene-sqlalchemy python3-graphql-core
  python3-graphql-relay python3-icalendar python3-maxminddb python3-promise python3-py python3-pytz-deprecation-shim python3-requests-file python3-rule-engine
  python3-rx python3-smoke-zephyr ruby-celluloid ruby-celluloid-io ruby-rubydns
Use 'sudo apt autoremove' to remove them.
The following packages have been kept back:
  libncurses-dev libncurses6 libncursesw6 libtinfo6 ncurses-bin ruby-celluloid
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
curl is already the newest version (7.88.1-11).
The following packages were automatically installed and are no longer required:
  gir1.2-gtksource-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 gobject-introspection king-phisher libavfilter8 libavformat59
  libblockdev-crypto2 libblockdev-fs2 libblockdev-loop2 libblockdev-part-err2 libblockdev-part2 libblockdev-swap2 libblockdev-utils2 libblockdev2 libcodec2-1.0
  libgdal32 libgeos3.11.1 libhttp-cookiejar-perl liblc3-0 libmongocrypt0 libmozilla-publicsuffix-perl libmujs2 libncurses5 libplacebo208 libpostproc56
  libsoup-gnome2.4-1 libspatialite7 libsuperlu5 libswscale6 libtinfo5 libwebsockets17 linux-image-6.1.0-kali7-amd64 pwgen python3-advancedhttpserver python3-boltons
  python3-cairo-dev python3-cryptography37 python3-flask-security python3-geoip2 python3-geojson python3-graphene python3-graphene-sqlalchemy python3-graphql-core
  python3-graphql-relay python3-icalendar python3-maxminddb python3-promise python3-py python3-pytz-deprecation-shim python3-requests-file python3-rule-engine
  python3-rx python3-smoke-zephyr ruby-celluloid ruby-celluloid-io ruby-rubydns
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (23.2+dfsg-1).
The following packages were automatically installed and are no longer required:
  gir1.2-gtksource-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 gobject-introspection king-phisher libavfilter8 libavformat59
  libblockdev-crypto2 libblockdev-fs2 libblockdev-loop2 libblockdev-part-err2 libblockdev-part2 libblockdev-swap2 libblockdev-utils2 libblockdev2 libcodec2-1.0
  libgdal32 libgeos3.11.1 libhttp-cookiejar-perl liblc3-0 libmongocrypt0 libmozilla-publicsuffix-perl libmujs2 libncurses5 libplacebo208 libpostproc56
  libsoup-gnome2.4-1 libspatialite7 libsuperlu5 libswscale6 libtinfo5 libwebsockets17 linux-image-6.1.0-kali7-amd64 pwgen python3-advancedhttpserver python3-boltons
  python3-cairo-dev python3-cryptography37 python3-flask-security python3-geoip2 python3-geojson python3-graphene python3-graphene-sqlalchemy python3-graphql-core
  python3-graphql-relay python3-icalendar python3-maxminddb python3-promise python3-py python3-pytz-deprecation-shim python3-requests-file python3-rule-engine
  python3-rx python3-smoke-zephyr ruby-celluloid ruby-celluloid-io ruby-rubydns
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

########################################################################
[*] Installing nim...
########################################################################
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nim is already the newest version (1.6.14-1).
The following packages were automatically installed and are no longer required:
  gir1.2-gtksource-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 gobject-introspection king-phisher libavfilter8 libavformat59
  libblockdev-crypto2 libblockdev-fs2 libblockdev-loop2 libblockdev-part-err2 libblockdev-part2 libblockdev-swap2 libblockdev-utils2 libblockdev2 libcodec2-1.0
  libgdal32 libgeos3.11.1 libhttp-cookiejar-perl liblc3-0 libmongocrypt0 libmozilla-publicsuffix-perl libmujs2 libncurses5 libplacebo208 libpostproc56
  libsoup-gnome2.4-1 libspatialite7 libsuperlu5 libswscale6 libtinfo5 libwebsockets17 linux-image-6.1.0-kali7-amd64 pwgen python3-advancedhttpserver python3-boltons
  python3-cairo-dev python3-cryptography37 python3-flask-security python3-geoip2 python3-geojson python3-graphene python3-graphene-sqlalchemy python3-graphql-core
  python3-graphql-relay python3-icalendar python3-maxminddb python3-promise python3-py python3-pytz-deprecation-shim python3-requests-file python3-rule-engine
  python3-rx python3-smoke-zephyr ruby-celluloid ruby-celluloid-io ruby-rubydns
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
[+] Nim Installed

########################################################################
[*] Installing mingW64 compiler...
########################################################################
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mingw-w64 is already the newest version (11.0.0-1).
The following packages were automatically installed and are no longer required:
  gir1.2-gtksource-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 gobject-introspection king-phisher libavfilter8 libavformat59
  libblockdev-crypto2 libblockdev-fs2 libblockdev-loop2 libblockdev-part-err2 libblockdev-part2 libblockdev-swap2 libblockdev-utils2 libblockdev2 libcodec2-1.0
  libgdal32 libgeos3.11.1 libhttp-cookiejar-perl liblc3-0 libmongocrypt0 libmozilla-publicsuffix-perl libmujs2 libncurses5 libplacebo208 libpostproc56
  libsoup-gnome2.4-1 libspatialite7 libsuperlu5 libswscale6 libtinfo5 libwebsockets17 linux-image-6.1.0-kali7-amd64 pwgen python3-advancedhttpserver python3-boltons
  python3-cairo-dev python3-cryptography37 python3-flask-security python3-geoip2 python3-geojson python3-graphene python3-graphene-sqlalchemy python3-graphql-core
  python3-graphql-relay python3-icalendar python3-maxminddb python3-promise python3-py python3-pytz-deprecation-shim python3-requests-file python3-rule-engine
  python3-rx python3-smoke-zephyr ruby-celluloid ruby-celluloid-io ruby-rubydns
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

########################################################################
[*] Installing Terraform...
########################################################################
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
terraform is already the newest version (1.5.5-0kali1).
The following packages were automatically installed and are no longer required:
  gir1.2-gtksource-3.0 gir1.2-javascriptcoregtk-4.0 gir1.2-soup-2.4 gir1.2-webkit2-4.0 gobject-introspection king-phisher libavfilter8 libavformat59
  libblockdev-crypto2 libblockdev-fs2 libblockdev-loop2 libblockdev-part-err2 libblockdev-part2 libblockdev-swap2 libblockdev-utils2 libblockdev2 libcodec2-1.0
  libgdal32 libgeos3.11.1 libhttp-cookiejar-perl liblc3-0 libmongocrypt0 libmozilla-publicsuffix-perl libmujs2 libncurses5 libplacebo208 libpostproc56
  libsoup-gnome2.4-1 libspatialite7 libsuperlu5 libswscale6 libtinfo5 libwebsockets17 linux-image-6.1.0-kali7-amd64 pwgen python3-advancedhttpserver python3-boltons
  python3-cairo-dev python3-cryptography37 python3-flask-security python3-geoip2 python3-geojson python3-graphene python3-graphene-sqlalchemy python3-graphql-core
  python3-graphql-relay python3-icalendar python3-maxminddb python3-promise python3-py python3-pytz-deprecation-shim python3-requests-file python3-rule-engine
  python3-rx python3-smoke-zephyr ruby-celluloid ruby-celluloid-io ruby-rubydns
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.

########################################################################
[*] Installing python requirements...
########################################################################
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/shinobix/PrimusC2/requirements.txt'

**Comment by Primusinterp** [comment]
Hello there, 

A commit was made fixing this issue with the hardcoded path in the `setup` script - please try again and let me know how it went.

**Comment by kali64amd** [comment]
It worked !!

Appreciate you'r help.
